import { makeStyles, tokens } from '@fluentui/react-components';

export const useStyles = makeStyles({
  root: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gridAutoRows: '18em',
    gap: '0.75em',
    width: '100%',
    padding: '0.75em',
    boxSizing: 'border-box',
    fontFamily: tokens.fontFamilyBase,
  },
  quadrant: {
    display: 'flex',
    flexDirection: 'column',
    borderRadius: '0.625em',
    overflow: 'hidden',
    height: '100%',
    boxSizing: 'border-box',
    boxShadow: tokens.shadow8,
    transition: 'box-shadow 0.2s ease, transform 0.2s ease',
    ':hover': {
      boxShadow: tokens.shadow16,
    },
  },
  quadrantHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0.625em 0.875em',
    fontWeight: tokens.fontWeightBold,
    fontSize: tokens.fontSizeBase500,
    letterSpacing: '0.02em',
    color: '#ffffff',
    userSelect: 'none',
  },
  headerBadge: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: '0.75em',
    padding: '0.0625em 0.5em',
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightRegular,
    lineHeight: '1.25em',
  },
  quadrantBody: {
    flex: 1,
    padding: '0.625em 0.75em',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5em',
    overflowY: 'auto',
    transition: 'background-color 0.15s ease',
  },
  quadrantBodyDragOver: {
    backgroundColor: 'rgba(0,0,0,0.07)',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5em',
    padding: '0.5em 0.75em',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: '0.5em',
    boxShadow: `inset 0 0 0 1px ${tokens.colorNeutralStroke2}, ${tokens.shadow2}`,
    cursor: 'grab',
    userSelect: 'none',
    transition: 'opacity 0.15s ease, box-shadow 0.15s ease, transform 0.1s ease',
    ':hover': {
      backgroundColor: 'rgba(255,255,255,0.92)',
      boxShadow: `inset 0 0 0 1px ${tokens.colorNeutralStroke1}, ${tokens.shadow4}`,
      transform: 'translateY(-0.0625em)',
    },
  },
  itemDragging: {
    opacity: '0.3',
    cursor: 'grabbing',
    transform: 'scale(0.97)',
  },
  itemDragOver: {
    borderTop: `0.125em solid ${tokens.colorBrandBackground}`,
    marginTop: '-0.0625em',
  },
  dragHandle: {
    color: tokens.colorNeutralStroke1,
    fontSize: '0.75em',
    lineHeight: 1,
    flexShrink: 0,
    letterSpacing: '-0.0625em',
    cursor: 'grab',
  },
  itemText: {
    flex: 1,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    wordBreak: 'break-word',
  },
  removeBtn: {
    minWidth: 'unset',
    padding: '0 0.25em',
    height: '1.375em',
    flexShrink: 0,
    opacity: '0',
    transition: 'opacity 0.15s ease',
  },
  itemHovered: {
    // applied via inline style trick; Griffel doesn't support parent-hover selectors
    // so we toggle this class via state instead
  },
  addRow: {
    display: 'flex',
    gap: '0.5em',
    padding: '0.5em 0.75em 0.75em',
    borderTop: `1px solid rgba(0,0,0,0.08)`,
    backgroundColor: 'rgba(255,255,255,0.45)',
    alignItems: 'center',
  },
  addInput: {
    flex: 1,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  addBtn: {
    minWidth: 'unset',
    width: '2.25em',
    height: '2.25em',
    padding: 0,
    borderRadius: '50%',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    border: 'none',
    transition: 'transform 0.15s ease, opacity 0.15s ease',
    ':hover': {
      transform: 'scale(1.18)',
      opacity: '0.85',
    },
  },
  addBtnIcon: {
    fontSize: '2em',
    display: 'block',
  },
});
